---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  BAZEL_STARTUP_FLAGS: --bazelrc=${{ github.workspace }}/.github/github.bazelrc

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Setup Bazelrc (Windows)
        run: |
          echo "startup --output_user_root=C:/bzl" > ./user.bazelrc
        if: startswith(runner.os, 'Windows')
      - name: Setup Bazelrc
        run: |
          echo "common --keep_going" >> ./user.bazelrc

      # Build and Test the code
      - name: Test (Unix)
        run: bazel ${BAZEL_STARTUP_FLAGS[@]} test //...
        if: startswith(runner.os, 'Windows') != true
      - name: Test (Windows)
        run: bazel $env:BAZEL_STARTUP_FLAGS test //...
        if: startswith(runner.os, 'Windows')
      
      # Build and test the examples
      - name: Examples string_sum (Unix)
        working-directory: ./examples/string_sum
        run: bazel ${BAZEL_STARTUP_FLAGS[@]} test //...
        if: startswith(runner.os, 'Windows') != true
      - name: Examples string_sum (Windows)
        working-directory: ./examples/string_sum
        run: bazel $env:BAZEL_STARTUP_FLAGS test //...
        if: startswith(runner.os, 'Windows')

  ci-buildifier:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - name: Download Buildifier
        run: |
          wget "https://github.com/bazelbuild/buildtools/releases/download/v8.0.3/buildifier-linux-amd64" -O buildifier
          chmod +x buildifier
      - name: Buildifier
        run: ./buildifier -lint=warn -mode=check -warnings=all -r ${{ github.workspace }}

  ci-lint-and-format:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          pip install 'black==24.10.0' 'isort==5.13.2' --user
      - name: Run black
        run: |
          python -m black --check --diff pyo3
      - name: Run isort
        run: |
          python -m isort --check-only pyo3
